repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.4
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
        args: [--respect-gitignore]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
      - id: debug-statements
      - id: check-case-conflict
      - id: mixed-line-ending
        args: [--fix=lf]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.9.0' # Use a recent version of mypy
    hooks:
      - id: mypy
        args: [--ignore-missing-imports, --scripts-are-modules]
        additional_dependencies:
          # Add any types-* dependencies needed by mypy that are in your project
          # For example:
          # - "types-requests"
          # From pyproject.toml:
          - "types-lxml"
          # Add other dependencies mypy needs to analyze the code
          - "fire"
          - "lxml"
          - "loguru"
          - "litellm>=1.67.2"
          - "python-dotenv"
          - "tenacity"
          - "rich"
          - "tiktoken"
          - "backoff"
          - "elevenlabs"
          - "pytest" # If testing mypy on tests too
